// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5m2Dm8zqPhHigw8GU0MRsRlcG-3EqfYs',
    appId: '1:969776856345:web:bb8379620248c728c3d988',
    messagingSenderId: '969776856345',
    projectId: 'assignment-a012c',
    authDomain: 'assignment-a012c.firebaseapp.com',
    storageBucket: 'assignment-a012c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWIV8d6UY10G3t--115sua2Nn_gLU3y5c',
    appId: '1:969776856345:android:b3f7468e4bd235eac3d988',
    messagingSenderId: '969776856345',
    projectId: 'assignment-a012c',
    storageBucket: 'assignment-a012c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfJWprzCOB1pEMFhY8n0tsfMhGpp8ur5M',
    appId: '1:969776856345:ios:03e47cf9af0f9063c3d988',
    messagingSenderId: '969776856345',
    projectId: 'assignment-a012c',
    storageBucket: 'assignment-a012c.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfJWprzCOB1pEMFhY8n0tsfMhGpp8ur5M',
    appId: '1:969776856345:ios:fdeb1154a363c63fc3d988',
    messagingSenderId: '969776856345',
    projectId: 'assignment-a012c',
    storageBucket: 'assignment-a012c.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
